apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provisioner-ng1
  template:
    metadata:
      labels:
        app: provisioner-ng1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/provisioner-name
                operator: In
                values:
                - provisioner-ng1
      containers:
      - name: webcolor
        image: peronw/web-page:green
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webcolor
spec:
  selector:
    app: webcolor
  ports:
  - port: 80  
    targetPort: 80
  type: LoadBalancer

